// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm0VuxA-YH7sqf0QfLI5dSL9jzCx6gGIQ',
    appId: '1:312625521666:web:eb6dfed533fdf0aecab31b',
    messagingSenderId: '312625521666',
    projectId: 'time-control-49f2b',
    authDomain: 'time-control-49f2b.firebaseapp.com',
    storageBucket: 'time-control-49f2b.appspot.com',
    measurementId: 'G-3D4FCML76K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo-LB00soFIe9iJFlkSph6EMzAmgcVF44',
    appId: '1:312625521666:android:9b724c4cb862cab8cab31b',
    messagingSenderId: '312625521666',
    projectId: 'time-control-49f2b',
    storageBucket: 'time-control-49f2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZTyJb26S-uPRcWHlACaU94hqGGWOONK4',
    appId: '1:312625521666:ios:b7503c6db3a1c25dcab31b',
    messagingSenderId: '312625521666',
    projectId: 'time-control-49f2b',
    storageBucket: 'time-control-49f2b.appspot.com',
    iosClientId: '312625521666-gugehaj3pap7l5k31hnaj59ech1iha8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZTyJb26S-uPRcWHlACaU94hqGGWOONK4',
    appId: '1:312625521666:ios:b7503c6db3a1c25dcab31b',
    messagingSenderId: '312625521666',
    projectId: 'time-control-49f2b',
    storageBucket: 'time-control-49f2b.appspot.com',
    iosClientId: '312625521666-gugehaj3pap7l5k31hnaj59ech1iha8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeControl',
  );
}
